version: "3.9"
services:
  validator:
    build:
      dockerfile: Dockerfile
      context: app/.
    env_file:
      - .env
    restart: unless-stopped
    expose:
      - "9090"
      - "1317"
      - "26656"
      - "26657"
    ports:
      - "9090:9090"
      - "1317:1317"
      - "26656:26656"
      - "26657:26657"
    logging:
      options:
        max-size: "12m"
        max-file: "5"
    networks:
      default:
    volumes:
      - ./app/custom-entrypoint.sh:/opt/custom-entrypoint.sh
      - ./app/helpers.sh:/opt/helpers.sh
      - celestia-app:/root/.celestia-app
  bridge:
    image: arashidos/celestia-node:v0.3.0-rc2
    env_file:
      - .env
    restart: unless-stopped
    command: "celestia bridge start --core.grpc $BRIDGE_CORE_GRPC --core.remote $BRIDGE_CORE_REMOTE --keyring.accname $BRIDGE_KEY_RING_ACC_NAME"
    logging:
      options:
        max-size: "12m"
        max-file: "5"
    networks:
      default:
    volumes:
      - celestia-bridge-node:/root/.celestia-bridge
volumes:
  celestia-app:
  celestia-bridge-node:
networks:
  default:
